{
 "title": "MegaRAID Health",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Host:",
    "query": {
     "query": "label_values(megaraid_controller_info, instance)"
    }
   },
   {
    "name": "controller",
    "label": "Controller RAID:",
    "query": {
     "query": "label_values(megaraid_pd_info{instance=~\"$node\"}, controller)"
    }
   },
   {
    "name": "enclosure",
    "label": "Enclosure:",
    "query": {
     "query": "label_values(megaraid_pd_info{instance=~\"$node\"}, enclosure)"
    }
   },
   {
    "name": "slot",
    "label": "Slot:",
    "query": {
     "query": "label_values(megaraid_pd_info{instance=~\"$node\"}, slot)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Controllers list",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "megaraid_controller_info{job=\"storcli\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(megaraid_degraded{job=\"storcli\"}) by (controller)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(megaraid_failed{job=\"storcli\"}) by (controller)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(megaraid_battery_backup_healthy{job=\"storcli\"}) by (controller)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(megaraid_healthy{job=\"storcli\"}) by (controller)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disks list",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "megaraid_pd_info{job=\"storcli\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(megaraid_pd_link_speed_gbps{job=\"storcli\"}) by (controller, enclosure, instance, slot)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(megaraid_pd_media_errors{job=\"storcli\"}) by (controller, enclosure, instance, slot)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(megaraid_pd_predictive_errors{job=\"storcli\"}) by (controller, enclosure, instance, slot)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(megaraid_pd_other_errors{job=\"storcli\"}) by (controller, enclosure, instance, slot)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(megaraid_pd_smart_alerted{job=\"storcli\"}) by (controller, enclosure, instance, slot)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Virtual groups list",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "megaraid_vd_info{job=\"storcli\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}